#!/usr/bin/env python3
"""x_search.py — complete read-only X (Twitter) client using the logged-in
browser session from the x-refresh project.

Covers the everyday "X in a browser" flows:
  search      search tweets/users (Top/Latest/People/Media/Lists)
  home        For You / Following timelines
  tweet       open a post and read its replies (TweetDetail)
  user        a profile's posts / replies / media / likes
  bookmarks   your saved posts
  likes       your liked posts

Credentials/proxy come from ~/x-refresh/config.json. Zero third-party
dependencies; every request goes through `curl` (robust retries behind flaky
proxies) via the configured proxy.

How it survives X's anti-hardcoding measures:
  * GraphQL queryIds rotate every few weeks  -> extracted LIVE from x.com's
    current JavaScript: main.js first, then the lazily-loaded chunks whose
    index is embedded in the home page (webpack runtime `.u=e=>`), swept in
    parallel, early-stopping once every op we need is found (per-op feature
    switches come from the same bundle snippets). Cached 24h in
    ~/.cache/x-search/state.json; on a 404 the cache is dropped, everything
    is re-extracted once, and the request retried.
  * SearchTimeline (search), UserTweetsAndReplies and Followers are extra
    gated: they require a per-request `x-client-transaction-id` header —
    single-use, generated by an algorithm ported verbatim (MIT) from
    iSarabjitDhiman/XClientTransaction, with inputs derived from the home
    page (verification meta, loading-anim SVG frames, ondemand.s indices).
    This script only calls SearchTimeline among the gated ops, and uses the
    ungated UserRepliesTimeline for profile replies.

Usage:
  x_search.py "DLSS 5"                          # legacy shorthand -> search
  x_search.py search "DLSS 5" --latest --pages 2
  x_search.py home --following -n 30
  x_search.py tweet https://x.com/user/status/123...
  x_search.py user nvidia --media
  x_search.py bookmarks --json
  x_search.py likes

Exit codes:
  0 ok            1 bad usage        2 auth/config problem
  3 runtime extraction failed (X rebuilt its client — re-port needed)
  4 X rejected the generated transaction-id (algorithm rotted)
  5 rate-limited (429)   6 request/pagination failure
"""
import argparse
import base64
import hashlib
import json
import math
import os
import random
import re
import subprocess
import sys
import threading
import time
import urllib.parse
from concurrent.futures import ThreadPoolExecutor
from datetime import datetime
from email.utils import parsedate_to_datetime
from html.parser import HTMLParser

try:  # never let a broken locale mangle results
    sys.stdout.reconfigure(encoding="utf-8")
    sys.stderr.reconfigure(encoding="utf-8")
except Exception:
    pass

# --- constants ---------------------------------------------------------------

BEARER = ("AAAAAAAAAAAAAAAAAAAAANRILgAAAAAAnNwIzUejRCOuH5E6I8xnZz4puTs"
          "%3D1Zv7ttfk8LF81IUq16cHjhLTvJu4FA33AGWWjCpTnA")
UA = ("Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) "
      "Chrome/120.0 Safari/537.36")
BUNDLE_BASE = "https://abs.twimg.com/responsive-web/client-web"
HOME_URL = "https://x.com/home"
CACHE_TTL = 24 * 3600
CACHE_PATH = os.path.expanduser("~/.cache/x-search/state.json")

#: every GraphQL op this client may call. Each must appear in one of x.com's
#: JS bundles with `queryId:"…",operationName:"<name>",operationType:"query"`.
WANTED_OPS = (
    "SearchTimeline", "HomeTimeline", "HomeLatestTimeline", "TweetDetail",
    "UserTweets", "UserMedia", "UserRepliesTimeline",
    "Bookmarks", "Likes", "UserByScreenName",
)
#: nice-to-have ops kept when present, never required (they only get a command
#: the day we wire one).
OPTIONAL_OPS = ("UserArticlesTweets", "UserHighlightsTweets", "TweetResultsByRestIds")

MAIN_JS_RE = re.compile(rf"{re.escape(BUNDLE_BASE)}/main\.[\w-]+\.js")
RECORD_RE = re.compile(
    r'queryId:"(?P<qid>[A-Za-z0-9_-]+)",operationName:"(?P<op>\w+)",'
    r'operationType:"(?P<typ>\w+)"')
METADATA_RE = re.compile(
    r'queryId:"(?P<qid>[A-Za-z0-9_-]+)",operationName:"(?P<op>\w+)",'
    r'operationType:"query",'
    r'metadata:\{featureSwitches:\[(?P<fs>[^\]]*)\]', re.S)

VERIFICATION_RE = re.compile(
    r'<meta[^>]+name=["\']twitter-site-verification["\'][^>]+content=["\']([^"\']+)["\']')
ON_DEMAND_FILE_RE = re.compile(r",(\d+):[\"']ondemand\.s[\"']")
ON_DEMAND_HASH_PATTERN = r',{}:"([0-9a-f]+)"'
ON_DEMAND_FILE_URL = BUNDLE_BASE + "/ondemand.s.{filename}a.js"
INDICES_RE = re.compile(r"(\(\w{1}\[(\d{1,2})\],\s*16\))+")
CHUNK_LOADER_MARKER = ".u=e=>"
CHUNK_PAIR_RE = re.compile(r'(\d+):"([^"]+)"')

EPOCH_OFFSET = 1682924400        # X's epoch: 2023-05-01T07:00:00Z
ADD_RANDOM = 3                   # upstream ADDITIONAL_RANDOM_NUMBER
TX_KEYWORD = "obfiowerehiring"   # upstream DEFAULT_KEYWORD
TOTAL_TIME = 4096

#: ops that answer 404 without a fresh x-client-transaction-id (live-probed).
#: Only SearchTimeline is used here, but keep the set explicit for clarity.
GATED_OPS = frozenset({"SearchTimeline", "UserTweetsAndReplies", "Followers"})

PRODUCTS = ("Top", "Latest", "People", "Media", "Lists")

#: fallback field toggles merged into the `features` query param (the same
#: with* keys X's own client passes alongside the per-op featureSwitches).
DEFAULT_FIELD_TOGGLE_KEYS = [
    "withPayments", "withAuxiliaryUserLabels", "withArticleRichContentState",
    "withArticlePlainText", "withArticleSummaryText", "withArticleVoiceOver",
    "withGrokAnalyze", "withDisallowedReplyControls",
]

#: ops requiring a non-empty `fieldToggles` query param (live-captured shapes).
FIELD_TOGGLES = {
    "TweetDetail": {
        "withArticleRichContentState": True, "withArticlePlainText": False,
        "withArticleSummaryText": True, "withArticleVoiceOver": True,
        "withGrokAnalyze": False, "withDisallowedReplyControls": False,
    },
}


# --- tiny http layer (curl subprocess: robust against slow proxies) ---------

class Http:
    """All requests go through `curl` with retries — urllib raw-bites are
    brittle behind flaky proxies, curl's retry logic handles them well.
    Returns (status:int, headers:dict[str,str], body:str)."""

    def __init__(self, cfg, max_time=90):
        self.proxy = cfg.get("proxy", "").strip()
        self.max_time = max_time

    def fetch(self, url, cookie=None, gql=None, txid=None, method="GET"):
        cmd = [
            "curl", "-sS", "--compressed", "-D", "-", "-X", method,
            "--max-time", str(self.max_time),
            "--retry", "2", "--retry-delay", "3", "--retry-all-errors",
            "-H", f"User-Agent: {UA}",
        ]
        if self.proxy:
            cmd += ["-x", self.proxy]
        if cookie:
            cmd += [
                "-H", f"Cookie: auth_token={cookie['auth_token']}; ct0={cookie['ct0']}",
                "-H", "Accept-Language: en-US,en;q=0.9",
                "-H", "Referer: https://x.com",
            ]
        if gql:
            cmd += [
                "-H", f"authorization: Bearer {BEARER}",
                "-H", "x-twitter-active-user: yes",
                "-H", "x-twitter-client-language: en",
                "-H", f"x-csrf-token: {gql['ct0']}",
                "-H", f"Cookie: auth_token={gql['auth_token']}; ct0={gql['ct0']}",
            ]
        if txid:
            cmd += ["-H", f"x-client-transaction-id: {txid}"]
        cmd += [url]

        out = None
        for attempt in range(2):  # belt &braces around curl-level hiccups
            try:
                out = subprocess.run(cmd, capture_output=True, timeout=self.max_time + 30)
                break
            except subprocess.TimeoutExpired:
                if attempt:
                    return -1, {}, "curl: outer timeout"
                continue
        if out is None or (out.returncode != 0 and not out.stdout):
            return -1, {}, ((f"curl exit {out.returncode}: " if out else "curl failed: ")
                            + out.stderr.decode("utf-8", "replace")[:200] if out else "")
        raw = out.stdout
        # curl -D - dumps EVERY header block: the proxy's CONNECT response and
        # any --retry attempts too. The REAL response is the LAST status line.
        statuses = list(re.finditer(rb"HTTP/[\d.]+\s+(\d+)[^\r\n]*", raw))
        if not statuses:
            return -1, {}, f"no HTTP status line in response: {raw[:200]!r}"
        last = statuses[-1]
        tail = raw[last.start():]
        sep = re.search(rb"\r\n\r\n|\n\n", tail)
        if not sep:
            return -1, {}, f"no header/body separator: {raw[:200]!r}"
        head, body = tail[:sep.start()], tail[sep.end():]
        headers = {}
        for line in head.decode("utf-8", "replace").splitlines()[1:]:
            if ":" in line:
                name, _, value = line.partition(":")
                headers[name.strip().lower()] = value.strip()
        return int(last.group(1)), headers, body.decode("utf-8", errors="replace")


def die(code, msg):
    print(f"error: {msg}", file=sys.stderr)
    sys.exit(code)


# --- x-client-transaction-id (ported verbatim from iSarabjitDhiman/XClientTransaction, MIT) ---

class _FrameParser(HTMLParser):
    """Collect the `d` attributes of the children of each loading-x-anim-N's
    first element child (mirrors upstream: list(frames.children)[0].children)."""

    def __init__(self):
        super().__init__(convert_charrefs=True)
        self.frames, self._active, self._depth = {}, None, 0

    def handle_starttag(self, tag, attrs):
        attrs = dict(attrs)
        if self._active is None:
            m = re.fullmatch(r"loading-x-anim-(\d+)", attrs.get("id") or "")
            if m:
                self._active = int(m.group(1))
                self.frames[self._active] = []
                self._depth = 0
            return
        self._depth += 1
        if self._depth == 2:
            self.frames[self._active].append(attrs.get("d") or "")

    def handle_endtag(self, tag):
        if self._active is None:
            return
        if self._depth == 0:
            self._active = None
            return
        self._depth -= 1


def _js_round(num):
    x = math.floor(num)
    if (num - x) >= 0.5:
        x = math.ceil(num)
    return math.copysign(x, num)


def _is_odd(num):
    return -1.0 if num % 2 else 0.0


def _float_to_hex(x):
    result = []
    quotient = int(x)
    fraction = x - quotient
    while quotient > 0:
        quotient = int(x / 16)
        remainder = int(x - (float(quotient) * 16))
        result.insert(0, chr(remainder + 55) if remainder > 9 else str(remainder))
        x = float(quotient)
    if fraction == 0:
        return "".join(result)
    result.append(".")
    while fraction > 0:
        fraction *= 16
        integer = int(fraction)
        fraction -= float(integer)
        result.append(chr(integer + 55) if integer > 9 else str(integer))
    return "".join(result)


def _cubic_value(curves, t):
    start_gradient = end_gradient = 0.0
    start, mid, end = 0.0, 0.0, 1.0
    if t <= 0.0:
        if curves[0] > 0.0:
            start_gradient = curves[1] / curves[0]
        elif curves[1] == 0.0 and curves[2] > 0.0:
            start_gradient = curves[3] / curves[2]
        return start_gradient * t
    if t >= 1.0:
        if curves[2] < 1.0:
            end_gradient = (curves[3] - 1.0) / (curves[2] - 1.0)
        elif curves[2] == 1.0 and curves[0] < 1.0:
            end_gradient = (curves[1] - 1.0) / (curves[0] - 1.0)
        return 1.0 + end_gradient * (t - 1.0)

    def calc(a, b, m):
        return 3.0 * a * (1 - m) * (1 - m) * m + 3.0 * b * (1 - m) * m * m + m * m * m

    while start < end:
        mid = (start + end) / 2
        x_est = calc(curves[0], curves[2], mid)
        if abs(t - x_est) < 0.00001:
            return calc(curves[1], curves[3], mid)
        if x_est < t:
            start = mid
        else:
            end = mid
    return calc(curves[1], curves[3], mid)


def _interpolate(from_list, to_list, f):
    return [a * (1 - f) + b * f for a, b in zip(from_list, to_list)]


def _rotation_matrix(rotation):
    rad = math.radians(rotation)
    return [math.cos(rad), -math.sin(rad), math.sin(rad), math.cos(rad)]


def _solve(value, min_val, max_val, rounding):
    result = value * (max_val - min_val) / 255 + min_val
    return math.floor(result) if rounding else round(result, 2)


def _animate(frame_row, target_time):
    from_color = [float(i) for i in [*frame_row[:3], 1]]
    to_color = [float(i) for i in [*frame_row[3:6], 1]]
    to_rotation = [_solve(float(frame_row[6]), 60.0, 360.0, True)]
    curves = [_solve(float(i), _is_odd(c), 1.0, False) for c, i in enumerate(frame_row[7:])]
    value = _cubic_value(curves, target_time)
    color = [max(0, min(255, i)) for i in _interpolate(from_color, to_color, value)]
    rotation = _interpolate([0.0], to_rotation, value)
    matrix = _rotation_matrix(rotation[0])
    parts = [format(round(i), "x") for i in color[:-1]]
    for i in matrix:
        rounded = round(i, 2)
        if rounded < 0:
            rounded = -rounded
        hex_value = _float_to_hex(rounded)
        parts.append(f"0{hex_value}".lower() if hex_value.startswith(".") else hex_value or "0")
    parts.extend(["0", "0"])
    return re.sub(r"[.-]", "", "".join(parts))


def compute_animation_key(key_bytes, frames, row_index_key, byte_indices):
    frame_paths = frames.get(key_bytes[5] % 4) or []
    if len(frame_paths) < 2:
        raise RuntimeError(
            f"loading-x-anim frame {key_bytes[5] % 4} has {len(frame_paths)} paths, expected >= 2")
    rows = [[int(n) for n in re.sub(r"[^\d]+", " ", seg).strip().split()]
            for seg in frame_paths[1][9:].split("C")]
    row_index = key_bytes[row_index_key] % 16
    frame_time = 1
    for i in byte_indices:
        frame_time *= key_bytes[i] % 16
    frame_time = _js_round(frame_time / 10) * 10
    if not rows:
        raise RuntimeError("frame row parsing produced no rows")
    return _animate(rows[row_index % len(rows)], float(frame_time) / TOTAL_TIME)


def mint_transaction_id(key_bytes, animation_key, method, path):
    """One fresh id per request; never cache or replay the result (single-use)."""
    time_now = math.floor((time.time() * 1000 - EPOCH_OFFSET * 1000) / 1000)
    time_bytes = [(time_now >> (i * 8)) & 0xFF for i in range(4)]
    digest = hashlib.sha256(
        f"{method}!{path}!{time_now}{TX_KEYWORD}{animation_key}".encode()).digest()
    payload = [*key_bytes, *time_bytes, *list(digest)[:16], ADD_RANDOM]
    noise = random.randint(0, 255)
    out = bytearray([noise, *[i ^ noise for i in payload]])
    return base64.b64encode(out).decode().strip("=")


# --- runtime ingredients (queryIds + features + txid inputs), live & cached --

def _scrape_ops(text):
    """operation -> queryId from one bundle; queries only (never mutations)."""
    found = {}
    for m in RECORD_RE.finditer(text):
        if m.group("typ") == "query":
            found[m.group("op")] = m.group("qid")
    return found


def _scrape_features(text, op_name, qid):
    """per-op featureSwitches keys from the same bundle snippet, all set true."""
    start = max(0, text.find(f'operationName:"{op_name}"', 0) - 200)
    m = METADATA_RE.search(text, start)
    if m and m.group("qid") == qid and m.group("op") == op_name:
        keys = re.findall(r'"([^"]+)"', m.group("fs"))
        if keys:
            return keys
    return None


def _brace_span(text, start):
    open_index = text.index("{", start)
    depth = 0
    for index in range(open_index, len(text)):
        if text[index] == "{":
            depth += 1
        elif text[index] == "}":
            depth -= 1
            if depth == 0:
                return text[open_index:index + 1], index + 1
    raise ValueError("unbalanced object literal")


def _chunk_urls(html):
    """Every lazily-loaded chunk URL x.com's own webpack loader can build.

    Provenance: agentic-x (MIT). The HTML inlines two id-keyed maps —
    `.u=e=> ... names ... hashes ... a.js` — which are the only complete
    index of what X serves."""
    marker = html.find(CHUNK_LOADER_MARKER)
    if marker == -1:
        return []
    try:
        names_literal, after = _brace_span(html, marker)
        hashes_literal, _ = _brace_span(html, after)
    except (ValueError, IndexError):
        return []
    names = dict(CHUNK_PAIR_RE.findall(names_literal))
    hashes = dict(CHUNK_PAIR_RE.findall(hashes_literal))
    return [f"{BUNDLE_BASE}/{names.get(cid, cid)}.{digest}a.js"
            for cid, digest in hashes.items()]


def extract_runtime(http, cookie, verbose=False):
    """Fetch the home page + relevant JS and derive every runtime ingredient:
    per-op {queryId, features}, plus txid key bytes / animation-key inputs.
    Ondemand indices & meta tag are cheap to re-derive on every refresh."""
    status, _, html = http.fetch(HOME_URL, cookie=cookie)
    if status in (401, 403):
        raise RuntimeError("x.com rejected the home page with %d — auth_token/ct0 "
                           "likely expired; update ~/x-refresh/config.json" % status)
    if status != 200:
        raise RuntimeError(f"could not fetch x.com/home (HTTP {status})")

    m = VERIFICATION_RE.search(html)
    if not m:
        raise RuntimeError("x.com served no twitter-site-verification meta tag")
    key_bytes = list(base64.b64decode(m.group(1).encode()))

    frames_parser = _FrameParser()
    frames_parser.feed(html)
    frames = frames_parser.frames
    if len(frames) < 4:
        raise RuntimeError(f"x.com served {len(frames)} loading-x-anim frames, expected 4")

    # txid indices from the ondemand.s chunk
    indices = None
    chunk_m = ON_DEMAND_FILE_RE.search(html)
    if chunk_m:
        hash_m = re.search(ON_DEMAND_HASH_PATTERN.format(chunk_m.group(1)), html)
        if hash_m:
            s, _, body = http.fetch(ON_DEMAND_FILE_URL.format(filename=hash_m.group(1)))
            if s == 200:
                idx = [int(x.group(2)) for x in INDICES_RE.finditer(body)]
                if len(idx) >= 2:
                    indices = idx
    if not indices:
        raise RuntimeError("ondemand.s chunk carried no key-byte indices")

    animation_key = compute_animation_key(key_bytes, frames, indices[0], indices[1:])

    # -- op harvest: main.js first, then lazily-loaded chunks until complete
    main_m = MAIN_JS_RE.search(html)
    if not main_m:
        raise RuntimeError("could not locate the main.js bundle URL in the home page")
    status, _, main_js = http.fetch(main_m.group(0))
    if status != 200:
        raise RuntimeError(f"could not fetch main.js (HTTP {status})")

    observed = {}          # op name -> queryId
    features_map = {}      # op name -> {featureSwitch key: True}
    missing = True
    wanted = set(WANTED_OPS)

    def harvest(text, label):
        nonlocal missing
        ops_found = _scrape_ops(text)
        got = []
        for op in WANTED_OPS + OPTIONAL_OPS:
            if op in ops_found and op not in observed:
                observed[op] = ops_found[op]
                fs = _scrape_features(text, op, ops_found[op])
                if fs:
                    features_map[op] = {k: True for k in fs}
                got.append(op)
        missing = bool(wanted - observed.keys())
        if got and verbose:
            print(f"[x-search] ops from {label}: "
                  + ", ".join(f"{o}={observed[o]}" for o in got), file=sys.stderr)

    harvest(main_js, "main.js")

    if missing:
        urls = _chunk_urls(html)
        if verbose:
            print(f"[x-search] sweeping {len(urls)} chunk URLs "
                  f"({len(wanted - observed.keys())} ops missing)…", file=sys.stderr)
        done_flag = threading.Event()

        class _Stop(Exception):
            pass

        def work(u):
            if done_flag.is_set():
                return ""
            try:
                s, _, body = http.fetch(u)
                return body if s == 200 else ""
            except Exception:
                return ""

        scanned = 0
        try:
            with ThreadPoolExecutor(max_workers=12) as pool:
                for text in pool.map(work, urls):
                    scanned += 1
                    if verbose and scanned % 50 == 0:
                        print(f"[x-search] …{scanned} chunks scanned", file=sys.stderr)
                    if not text:
                        continue
                    harvest(text, f"chunk #{scanned}")
                    if not missing:
                        done_flag.set()
                        raise _Stop
        except _Stop:
            pass

    missing_ops = [op for op in WANTED_OPS if op not in observed]
    if missing_ops:
        raise RuntimeError(
            f"x.com's JavaScript carried no {', '.join(missing_ops)} — "
            "X rebuilt its client; this script needs a re-port")

    # merge fallback toggle keys into every op's features (mirrors prior
    # working behaviour where the shared features map was accepted by all ops).
    # If a snippet carried no metadata, reuse the first harvested set — X's
    # ops largely share the same switches.
    runtime_features = {}
    fallback = next(iter(features_map.values()), None)
    for op in observed:
        feats = dict(features_map.get(op) or fallback or {})
        for k in DEFAULT_FIELD_TOGGLE_KEYS:
            feats[k] = True
        runtime_features[op] = feats
    if not any(runtime_features.values()):
        raise RuntimeError("feature switches could not be harvested from any bundle")

    runtime = {
        "extracted_at": time.time(),
        "ops": observed,          # op name -> queryId
        "features": runtime_features,  # op name -> features dict
        "key_bytes": key_bytes,
        "animation_key": animation_key,
        "indices": indices,
    }
    if verbose:
        print(f"[x-search] runtime extracted: {len(observed)} ops, "
              f"txid inputs key_bytes={keybytes_brief(key_bytes)} indices={indices[:4]}", file=sys.stderr)
        for op in sorted(observed):
            print(f"[x-search]   {op}: {observed[op]} (features={len(runtime_features.get(op, {}))})",
                  file=sys.stderr)
    try:
        os.makedirs(os.path.dirname(CACHE_PATH), exist_ok=True)
        with open(CACHE_PATH, "w") as f:
            json.dump(runtime, f)
    except Exception:
        pass
    return runtime


def keybytes_brief(kb):
    return "[" + ",".join(str(x) for x in kb[:4]) + ",…]"


def load_runtime(http, cookie, no_cache=False, verbose=False):
    if not no_cache:
        try:
            with open(CACHE_PATH) as f:
                runtime = json.load(f)
            if (time.time() - runtime.get("extracted_at", 0) < CACHE_TTL
                    and runtime.get("ops") and runtime.get("features")
                    and runtime.get("key_bytes") and runtime.get("animation_key")):
                needed = {op: runtime["ops"].get(op) for op in WANTED_OPS}
                if all(needed.values()):
                    if verbose:
                        print("[x-search] using cached runtime ingredients", file=sys.stderr)
                    return runtime
        except Exception:
            pass
    return extract_runtime(http, cookie, verbose=verbose)


# --- graphql call -------------------------------------------------------------

def gql_call(http, cfg, runtime, op, variables, cursor=None, verbose=False):
    """One GraphQL request. Mint a txid only for the gated ops."""
    variables = dict(variables)
    if cursor:
        variables["cursor"] = cursor
    qid = runtime["ops"][op]
    path = f"/i/api/graphql/{qid}/{op}"
    features = dict(runtime["features"].get(op) or next(iter(runtime["features"].values())))
    qs = {
        "variables": json.dumps(variables, separators=(",", ":")),
        "features": json.dumps(features, separators=(",", ":")),
    }
    toggles = FIELD_TOGGLES.get(op)
    if toggles is not None:
        qs["fieldToggles"] = json.dumps(toggles, separators=(",", ":"))
    url = f"https://x.com{path}?" + urllib.parse.urlencode(qs)
    txid = None
    if op in GATED_OPS:
        txid = mint_transaction_id(runtime["key_bytes"], runtime["animation_key"], "GET", path)
    status, headers, body = http.fetch(url, gql=cfg, txid=txid)
    if verbose:
        print(f"[x-search] GET {op} ({len(json.dumps(variables))}B vars) "
              f"txid={'yes' if txid else 'no'} -> HTTP {status}", file=sys.stderr)
    if status == 200:
        try:
            return json.loads(body), status, headers
        except json.JSONDecodeError:
            return None, -1, headers
    return None, status, headers


def paginate(http, cfg, runtime, op, variables, parse, pages, verbose=False):
    """Request `op` page-by-page via the bottom cursor. `parse` gets the JSON
    payload and returns (items, users, next_cursor). Resilient to the worst
    mid-run failure modes: 404 self-heal (re-extract once), 429 exit 5."""
    items_all, users_all = [], []
    cursor = None
    page = 0
    retried = False
    while page < pages:
        payload, status, headers = gql_call(http, cfg, runtime, op, variables,
                                            cursor=cursor, verbose=verbose)
        if payload is None:
            if status == 429:
                reset = headers.get("x-rate-limit-reset")
                hint = ""
                try:
                    hint = ("; bucket resets at "
                            + time.strftime("%Y-%m-%d %H:%M:%S", time.localtime(int(reset)))) if reset else ""
                except Exception:
                    pass
                die(5, f"rate-limited by X (429) on {op}{hint} "
                      f"[limit {headers.get('x-rate-limit-limit')}, "
                      f"remaining {headers.get('x-rate-limit-remaining')}] — "
                      f"fewer --pages or retry later")
            if status in (401, 403):
                die(2, f"X rejected the credentials (HTTP {status}) — update "
                      f"auth_token/ct0 in the x-refresh config")
            if status == 404 and not retried:
                retried = True  # only once, across the whole pagination
                if verbose:
                    print("[x-search] 404 — re-extracting runtime & retrying once…", file=sys.stderr)
                try:
                    runtime_new = extract_runtime(http, {"auth_token": cfg["auth_token"],
                                                        "ct0": cfg["ct0"]}, verbose=verbose)
                except RuntimeError:
                    # fall through to the rejection message below
                    pass
                else:
                    runtime.clear()
                    runtime.update(runtime_new)
                    continue
            if status == 404:
                die(4, f"X returned 404 for {op} — the queryId/algorithm has "
                      f"likely rotted after an X client redeploy. Re-port needed "
                      f"(https://github.com/iSarabjitDhiman/XClientTransaction "
                      f"for the txid generator)")
            die(6, f"X request failed for {op} (HTTP {status})")
        page += 1
        if "errors" in payload and not payload.get("data"):
            die(6, f"X API errors: {json.dumps(payload['errors'][:3], ensure_ascii=False)}")
        try:
            items, users, next_cursor = parse(payload)
        except Exception as ex:
            die(6, f"failed to parse the {op} response: {ex}")
        items_all.extend(items)
        users_all.extend(users)
        if not next_cursor:
            break
        cursor = next_cursor
        if page < pages:
            time.sleep(2.5)  # light pacing between pages
    return items_all, users_all, page


# --- parsing ------------------------------------------------------------------

def find_instructions(payload, depth=0):
    """Recursively locate the first `instructions` list in the payload. Every
    timeline-flavoured op nests it under a different root; this keeps the
    parser resilient to X renaming those roots."""
    if depth > 6 or not isinstance(payload, dict):
        return []
    for k, v in payload.items():
        if k == "instructions" and isinstance(v, list):
            return v
        found = find_instructions(v, depth + 1)
        if found:
            return found
    return []


def parse_user(u):
    core = u.get("core", {}) or {}
    legacy = u.get("legacy", {}) or {}
    return {
        "screen_name": core.get("screen_name") or u.get("rest_id", ""),
        "name": core.get("name", ""),
        "verified": bool(u.get("is_blue_verified")),
        "description": (u.get("profile_bio", {}) or {}).get("description", "")
                        or legacy.get("description", ""),
        "location": ((u.get("location", {}) or {}).get("location"))
                    or legacy.get("location", ""),
        "followers": legacy.get("followers_count"),
        "following": legacy.get("friends_count"),
        "tweets": legacy.get("statuses_count"),
        "rest_id": u.get("rest_id"),
    }


def parse_tweet(tr):
    if tr.get("__typename") == "TweetWithVisibilityResults":
        tr = tr.get("tweet", {})
    legacy = tr.get("legacy", {}) or {}
    if not legacy and tr.get("tweet", {}):
        tr = tr["tweet"]
        legacy = tr.get("legacy", {}) or {}
    note = ((tr.get("note_tweet", {}) or {})
            .get("note_tweet_results", {}).get("result", {}) or {})
    text = note.get("text") or legacy.get("full_text", "")
    user = (tr.get("core", {}) or {}).get("user_results", {}).get("result", {}) or {}
    udata = parse_user(user)
    try:
        dt = parsedate_to_datetime(legacy.get("created_at", ""))
        created_iso = dt.isoformat()
    except Exception:
        dt = None
        created_iso = legacy.get("created_at", "")
    views = tr.get("views", {}).get("count")
    return {
        "id": tr.get("rest_id"),
        "created_at": legacy.get("created_at", ""),
        "iso": created_iso,
        "text": text,
        "author": udata,
        "url": f"https://x.com/{udata['screen_name']}/status/{tr.get('rest_id', '')}",
        "views": int(views) if views else None,
        "likes": legacy.get("favorite_count"),
        "retweets": legacy.get("retweet_count"),
        "replies": legacy.get("reply_count"),
        "quotes": legacy.get("quote_count"),
        "bookmarks": legacy.get("bookmark_count"),
        "lang": legacy.get("lang"),
        "is_retweet": "RT @" in legacy.get("full_text", "")[:5],
        "sensitive": bool(legacy.get("possibly_sensitive")),
        "in_reply_to": legacy.get("in_reply_to_status_id_str"),
    }


def parse_entries(payload, verbose=False):
    """Get (tweets, users, next_cursor) from any instructions list. Handles
    plain items, cursor entries and the conversation modules TweetDetail uses."""
    instructions = find_instructions(payload)
    tweets, users, next_cursor = [], [], None
    for ins in instructions:
        for e in ins.get("entries", []):
            eid = e.get("entryId", "")
            content = e.get("content", {}) or {}
            if content.get("entryType") == "TimelineTimelineCursor" or eid.startswith("cursor"):
                if content.get("cursorType") == "Bottom" or eid.startswith("cursor-bottom"):
                    next_cursor = content.get("value")
                continue
            if content.get("entryType") == "TimelineTimelineModule":
                for item in content.get("items", []):
                    ic = (item.get("itemContent", {}) or {}).get("itemContent", {}) \
                         or (item.get("item", {}) or {}).get("itemContent", {}) \
                         or item.get("itemContent", {}) or {}
                    tr = (ic.get("tweet_results", {}) or {}).get("result")
                    if tr:
                        tweets.append(parse_tweet(tr))
                continue
            ic = content.get("itemContent", {}) or {}
            if isinstance(ic.get("tweet_results"), dict) and ic["tweet_results"].get("result"):
                tweets.append(parse_tweet(ic["tweet_results"]["result"]))
            elif isinstance(ic.get("user_results"), dict) and ic["user_results"].get("result"):
                users.append(parse_user(ic["user_results"]["result"]))
            elif verbose:
                print(f"[x-search] skipped entry {eid or content.get('entryType')}",
                      file=sys.stderr)
    seen, dedup_t = set(), []
    for t in tweets:
        if t["id"] not in seen:
            seen.add(t["id"])
            dedup_t.append(t)
    seen, dedup_u = set(), []
    for u in users:
        key = u["screen_name"]
        if key not in seen:
            seen.add(key)
            dedup_u.append(u)
    return dedup_t, dedup_u, next_cursor


# --- output -------------------------------------------------------------------

def local_time(iso):
    try:
        return parsedate_to_datetime(iso).astimezone().strftime("%Y-%m-%d %H:%M")
    except Exception:
        try:
            return datetime.fromisoformat(iso).astimezone().strftime("%Y-%m-%d %H:%M")
        except Exception:
            return ""


def relative_time(iso):
    try:
        try:
            dt = parsedate_to_datetime(iso)
        except Exception:
            dt = datetime.fromisoformat(iso)
        diff = (datetime.now().astimezone() - dt).total_seconds()
        if diff < 3600:
            return f"{max(int(diff // 60), 0)}m ago" if diff < 3600 else ""
        if diff < 86400:
            return f"{int(diff // 3600)}h ago"
        return f"{int(diff // 86400)}d ago"
    except Exception:
        return ""


def print_tweets(tweets, title=None):
    if title:
        print(title)
    for i, t in enumerate(tweets, 1):
        a = t["author"]
        tick = " ✔" if a["verified"] else ""
        rel = relative_time(t["iso"])
        local = local_time(t["iso"])
        stamp = f"{local} ({rel})" if rel or local else ""
        reply_info = ""
        if t.get("in_reply_to"):
            reply_info = f"  ↩ reply"  # in_reply_to_status_id; replyee unknown w/o extra lookup
        print(f'{i}. {a["name"]} (@{a["screen_name"]}){tick}  {stamp}{reply_info}')
        print(f'   {t["url"]}')
        print(f'   {t["text"]}')
        stats = []
        for label, v in (("views", t["views"]), ("likes", t["likes"]),
                         ("RTs", t["retweets"]), ("replies", t["replies"]),
                         ("quotes", t["quotes"]), ("bookmarks", t["bookmarks"])):
            if v:
                stats.append(f"{label} {v}")
        if t["lang"]:
            stats.append(f"lang={t['lang']}")
        if stats:
            print("   · " + "  ".join(stats))
        print()


def print_users(users):
    for i, u in enumerate(users, 1):
        tick = " ✔" if u["verified"] else ""
        extras = []
        if u.get("followers") is not None:
            extras.append(f"followers {u['followers']}")
        if u.get("location"):
            extras.append(u["location"])
        line = f'{i}. {u["name"]} (@{u["screen_name"]}){tick}' + \
               (f"  [{', '.join(extras)}]" if extras else "")
        print(line)
        if u["description"]:
            print(f'   {u["description"]}')
        print()


# --- commands -----------------------------------------------------------------

def cmd_search(http, cfg, runtime, args):
    product = ("People" if args.people else
               ("Latest" if args.latest else (args.product or "Top")))
    variables = {
        "rawQuery": args.query,
        "count": args.count,
        "querySource": "typed_query",
        "product": product,
        "withGrokTranslatedBio": product in ("Top", "People"),
        "withQuickPromoteEligibilityTweetFields": False,
    }
    tweets, users, page = paginate(http, cfg, runtime, "SearchTimeline",
                                   variables, parse_entries, args.pages,
                                   verbose=args.verbose)
    is_people = product == "People"
    label = "users" if is_people else "tweets"
    items = users if is_people else tweets
    if args.json:
        print(json.dumps({
            "query": args.query, "product": product, "pages_fetched": page,
            "tweets": tweets, "users": users,
        }, ensure_ascii=False, indent=1))
        return
    print(f'X search — query: {args.query!r}  product: {product}  '
          f'pages: {page}/{args.pages}  {label}: {len(items)}')
    if is_people:
        print_users(users)
    else:
        print_tweets(tweets)
    if not items:
        print("(no results — try --latest, a broader query, or different operators)")


def cmd_home(http, cfg, runtime, args):
    op = "HomeLatestTimeline" if args.following else "HomeTimeline"
    tab = "Following" if args.following else "For You"
    variables = {
        "count": args.count,
        "includePromotedContent": True,
        "latestControlAvailable": True,
        "requestContext": "launch",
        "withCommunity": True,
    }
    tweets, users, page = paginate(http, cfg, runtime, op, variables,
                                  parse_entries, args.pages, verbose=args.verbose)
    if args.json:
        print(json.dumps({"timeline": tab, "op": op, "pages_fetched": page,
                          "tweets": tweets, "users": users},
                         ensure_ascii=False, indent=1))
        return
    print(f'X home — tab: {tab}  pages: {page}/{args.pages}  posts: {len(tweets)}')
    print_tweets(tweets)


def _extract_tweet_id(arg):
    m = re.search(r"(?:status/|statuses/)(\d{5,25})", arg)
    if m:
        return m.group(1)
    if re.fullmatch(r"\d{5,25}", arg):
        return arg
    die(1, f"could not read a tweet id from {arg!r} — pass a "
           f"https://x.com/<user>/status/<id> URL or the bare id")


def cmd_tweet(http, cfg, runtime, args):
    tweet_id = _extract_tweet_id(args.tweet)
    variables = {
        "focalTweetId": tweet_id,
        "with_rux_injections": False,
        "rankingMode": "Relevance",
        "includePromotedContent": True,
        "withCommunity": True,
        "withQuickPromoteEligibilityTweetFields": True,
        "withBirdwatchNotes": True,
        "withVoice": True,
    }
    tweets, users, page = paginate(http, cfg, runtime, "TweetDetail",
                                   variables, parse_entries, args.pages,
                                   verbose=args.verbose)
    focal = next((t for t in tweets if t["id"] == tweet_id), None)
    # Order the way a browser shows: ancestors-of-focal (root-first), focal, then
    # every other tweet in the conversation as replies.
    ancestors, replies_ordered = [], []
    if focal:
        chain = {t["id"]: t for t in tweets if t["id"] != focal["id"]}
        cursor_id = focal.get("in_reply_to")
        while cursor_id and cursor_id in chain:
            t = chain.pop(cursor_id)
            ancestors.insert(0, t)
            cursor_id = t.get("in_reply_to")
        order = {t["id"]: i for i, t in enumerate(tweets)}
        replies_ordered = sorted(chain.values(), key=lambda t: order.get(t["id"], 0))
    else:
        replies_ordered = tweets
    if args.json:
        print(json.dumps({"tweet_id": tweet_id, "focal": focal,
                          "ancestors": ancestors, "replies": replies_ordered,
                          "pages_fetched": page},
                         ensure_ascii=False, indent=1))
        return
    print(f'X thread — focal: {tweet_id}  pages: {page}/{args.pages}  '
          f'posts: {len(tweets)} (focal + {len(ancestors)} ancestors + {len(replies_ordered)} replies)')
    if ancestors:
        print("── thread (背景) " + "─" * 30)
        print_tweets(ancestors, None)
    if focal:
        print("── 主帖 " + "─" * 40)
        print_tweets([focal])
    if replies_ordered:
        print("── 回复 " + "─" * 41)
        print_tweets(replies_ordered)
    if not tweets:
        print("(no results — is the tweet id correct? deleted/private tweets return nothing)")


def _resolve_user_id(http, cfg, runtime, handle, verbose=False):
    handle = handle.lstrip("@")
    variables = {"screen_name": handle, "withSafetyModeUserFields": True}
    payload, status, headers = gql_call(http, cfg, runtime, "UserByScreenName",
                                        variables, verbose=verbose)
    if payload is None:
        die(6 if status != 404 else 4, f"UserByScreenName failed (HTTP {status}) for @{handle}")
    u = payload.get("data", {}).get("user", {}).get("result", {})
    rest_id = u.get("rest_id")
    if not rest_id:
        if u.get("__typename") == "UserUnavailable":
            die(1, f"@{handle} is unavailable ({u.get('reason', 'suspended/protected')})")
        die(6, f"could not resolve @{handle} to a user id")
    return rest_id, parse_user(u)


TAB_OPS = {
    "posts": "UserTweets",
    "replies": "UserRepliesTimeline",
    "media": "UserMedia",
    "likes": "Likes",
}


def _user_timeline_variables(op, user_id, count):
    if op == "UserTweets":
        return {"userId": user_id, "count": count, "includePromotedContent": False,
                "withQuickPromoteEligibilityTweetFields": True, "withVoice": True}
    # profile-tab shape shared by UserMedia / UserRepliesTimeline / Likes
    # (agentic-x live-captured; only Highlights differs, and we don't call it)
    return {"userId": user_id, "count": count, "includePromotedContent": False,
            "withClientEventToken": False, "withBirdwatchNotes": False,
            "withVoice": True}


def cmd_user(http, cfg, runtime, args):
    handle = args.handle.lstrip("@")
    rest_id, udata = _resolve_user_id(http, cfg, runtime, handle, verbose=args.verbose)
    tab = "media" if args.media else ("replies" if args.replies else "posts")
    op = TAB_OPS[tab]
    variables = _user_timeline_variables(op, rest_id, args.count)
    if op == "Likes" and cfg.get("user_id") and rest_id != cfg["user_id"]:
        print(f"WARN: X made likes private — @{handle}'s likes will usually return "
              f"empty unless it's your own account.", file=sys.stderr)
    tweets, users, page = paginate(http, cfg, runtime, op, variables,
                                   parse_entries, args.pages, verbose=args.verbose)
    if args.json:
        print(json.dumps({"handle": handle, "user_id": rest_id, "profile": udata,
                          "tab": tab, "op": op, "pages_fetched": page,
                          "tweets": tweets, "users": users},
                         ensure_ascii=False, indent=1))
        return
    print(f'X @{handle} — tab: {tab} ({op})  pages: {page}/{args.pages}  '
          f'posts: {len(tweets)}')
    print_tweets(tweets)
    if not tweets:
        print('(no results — wrong handle, empty tab, or a protected account)')


def cmd_bookmarks(http, cfg, runtime, args):
    variables = {"count": args.count, "includePromotedContent": False}
    tweets, users, page = paginate(http, cfg, runtime, "Bookmarks",
                                   variables, parse_entries, args.pages,
                                   verbose=args.verbose)
    if args.json:
        print(json.dumps({"pages_fetched": page, "tweets": tweets,
                          "users": users}, ensure_ascii=False, indent=1))
        return
    print(f'X bookmarks — pages: {page}/{args.pages}  posts: {len(tweets)}')
    print_tweets(tweets)


def cmd_likes(http, cfg, runtime, args):
    mine = cfg.get("user_id")
    if not mine:
        die(2, "config.json has no user_id — add it (numeric id) to read your likes")
    variables = _user_timeline_variables("Likes", mine, args.count)
    tweets, users, page = paginate(http, cfg, runtime, "Likes",
                                   variables, parse_entries, args.pages,
                                   verbose=args.verbose)
    if args.json:
        print(json.dumps({"pages_fetched": page, "tweets": tweets,
                          "users": users}, ensure_ascii=False, indent=1))
        return
    print(f'X likes — pages: {page}/{args.pages}  posts: {len(tweets)}')
    print_tweets(tweets)


# --- plumbing -----------------------------------------------------------------

def _shared_options(p):
    p.add_argument("-n", "--count", type=int, default=20,
                   help="items per page, 1-100 (default 20; X often returns fewer)")
    p.add_argument("--pages", type=int, default=1,
                   help="up to N pages via the bottom cursor (default 1, max 5)")
    p.add_argument("--json", action="store_true", help="machine-readable JSON only")
    p.add_argument("--config", default=os.path.expanduser("~/x-refresh/config.json"),
                   help="path to the x-refresh config.json")
    p.add_argument("--no-cache", action="store_true",
                   help="force re-extraction of queryId/transaction-id ingredients")
    p.add_argument("-v", "--verbose", action="store_true", help="diagnostics to stderr")


def main():
    ap = argparse.ArgumentParser(
        description="Read X (Twitter) with the x-refresh logged-in session: "
                    "search, timelines, threads, profiles, bookmarks, likes.",
        epilog='X query operators (search): from:, to:, since:, until:, '
               'min_faves:, lang:, is:reply, -filter:replies, "exact phrase", OR, …')
    subs = ap.add_subparsers(dest="cmd")

    def sp(name, help):
        p = subs.add_parser(name, help=help)
        _shared_options(p)
        return p

    lp = sp("search", 'search tweets/users (default command)')
    lp.add_argument("query", help='X search query, e.g. "DLSS 5", from:nvidia dlss')
    lp.add_argument("--product", default=None, choices=PRODUCTS,
                    help="X search tab: Top (default), Latest, People, Media, Lists")
    lp.add_argument("--latest", action="store_true", help="shorthand for --product Latest")
    lp.add_argument("--people", action="store_true", help="shorthand for --product People")

    hp = sp("home", "your home timeline")
    hpg = hp.add_mutually_exclusive_group()
    hpg.add_argument("--following", action="store_true", default=False,
                     help="the Following tab (default is For You)")
    hpg.add_argument("--for-you", action="store_true", default=False, dest="for_you",
                     help="the For You tab (the default)")

    tp = sp("tweet", "a post + its thread/replies")
    tp.add_argument("tweet", help="tweet URL or bare id")

    up = sp("user", "a profile's timeline (posts / replies / media / likes)")
    up.add_argument("handle", help="screen name, @-prefixed ok")
    upg = up.add_mutually_exclusive_group()
    upg.add_argument("--media", action="store_true", help="media tab")
    upg.add_argument("--replies", action="store_true", help="replies tab")

    bp = sp("bookmarks", "your bookmarked posts")
    kp = sp("likes", "your liked posts")

    # legacy shorthand: first arg starting with '-' after a bare query, or any
    # bare first arg, is treated as a search query
    argv = sys.argv[1:]
    known_cmds = {"search", "home", "tweet", "user", "bookmarks", "likes"}
    if argv and argv[0] not in known_cmds and not argv[0].startswith("-"):
        argv = ["search"] + argv
    elif argv and argv[0].startswith("-") and argv[0] not in ("-h", "--help"):
        # bare query was passed with flags only? require it
        argv = ["search", *argv]
    args = ap.parse_args(argv)

    # normalize limits
    args.count = max(1, min(100, getattr(args, "count", 20)))
    args.pages = max(1, min(5, getattr(args, "pages", 1)))

    if not args.cmd:
        ap.print_help()
        sys.exit(1)
    if args.cmd == "search" and not getattr(args, "query", None):
        die(1, "search needs a query argument")

    try:
        with open(os.path.expanduser(args.config)) as f:
            cfg = json.load(f)
    except FileNotFoundError:
        die(2, f"config not found: {args.config} (expected x-refresh's config.json "
               "with auth_token/ct0/proxy)")
    except Exception as ex:
        die(2, f"could not parse config {args.config}: {ex}")
    for k in ("auth_token", "ct0"):
        if not cfg.get(k):
            die(2, f"{k} missing in {args.config}")

    http = Http(cfg)
    cookie = {"auth_token": cfg["auth_token"], "ct0": cfg["ct0"]}
    try:
        runtime = load_runtime(http, cookie, no_cache=args.no_cache, verbose=args.verbose)
    except RuntimeError as ex:
        die(3, str(ex))

    dispatch = {
        "search": cmd_search, "home": cmd_home, "tweet": cmd_tweet,
        "user": cmd_user, "bookmarks": cmd_bookmarks, "likes": cmd_likes,
    }
    dispatch[args.cmd](http, cfg, runtime, args)


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        sys.exit(130)